DROP TABLE IF EXISTS cartline;
DROP TABLE IF EXISTS orderline;
DROP TABLE IF EXISTS orderstatus;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS menuitems;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS cart;